version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8680:80"
    volumes:
      - C:/xampp/htdocs/php-project/car.am:/var/www/html:Z
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_db
      - DB_DATABASE=cars_schema
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=zxcft741012
    container_name: caram
    image: caram-web
    stdin_open: true
    tty: true

  mysql_db:
    image: mysql:8.0
    ports:
      - "3507:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=zxcft741012
      - MYSQL_DATABASE=cars_schema

volumes:
  db_data:
